name: glp
channels:
  - bioconda
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python
  - ipykernel
  - numpy
  - numba
  - scipy
  - scikit-image
  - tqdm
  - xarray
  - dask
  - pandas
  - matplotlib
  - torchinfo
  - ipywidgets
  - phate
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1